### Register
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "first_name": "Saleh",
    "last_name": "Zaidan",
    "username": "13318006",
    "email": "saleh@skullers.com",
    "password": "13318006",
    "password2": "13318006"
}


### Login
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "13318006",
    "password": "13318006"
}


### Logout
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token 


### List students
GET http://127.0.0.1:8000/api/students/


### List groups
GET http://127.0.0.1:8000/api/groups/


### List class year
GET http://127.0.0.1:8000/api/class-year/


### Retrieve student
GET http://127.0.0.1:8000/api/auth/profile
Authorization: Token 


### Retrieve group
GET http://127.0.0.1:8000/api/auth/profile/group/
Authorization: Token 

