### Register
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "first_name": "Irina",
    "last_name": "Mardhatillah",
    "username": "13319090",
    "email": "irina@skullers.com",
    "password": "13319090",
    "password2": "13319090"
}

### Generate new pair of token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "13319090",
    "password": "13319090"
}


### Use refresh token to obtain new access token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTYyNTMxOTYzMSwianRpIjoiNGM1ZmZhMjk0MWUxNDk2ODlhZDIxM2U5MmJjYTM3MWYiLCJ1c2VyX2lkIjoxMX0.mStnEil0R19cYXewB73QI5MbNIDP2B__N9nw7MOF408"
}


### List students
GET http://127.0.0.1:8000/api/students/


### List groups
GET http://127.0.0.1:8000/api/groups/


### List class year
GET http://127.0.0.1:8000/api/class-year/


### Retrieve student
GET http://127.0.0.1:8000/api/auth/profile
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI1MjMzNTMxLCJqdGkiOiIzOTk4NzU1YjU1ZWU0YTNhYmY4MGM1YTBjMzA3NmZlOSIsInVzZXJfaWQiOjExfQ.Nr548wEcyad6F4qUEbhyeyphE0H4zwKVejy232D9SY8


### Retrieve group
GET http://127.0.0.1:8000/api/auth/profile/group/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI1MjMzNTMxLCJqdGkiOiIzOTk4NzU1YjU1ZWU0YTNhYmY4MGM1YTBjMzA3NmZlOSIsInVzZXJfaWQiOjExfQ.Nr548wEcyad6F4qUEbhyeyphE0H4zwKVejy232D9SY8

