### AUTH

### Register
POST http://127.0.0.1:8000/auth/register/
Content-Type: application/json

{
    "first_name": "Irina",
    "last_name": "Mardhatillah",
    "username": "13319090",
    "email": "irina@skullers.com",
    "password": "13319090",
    "password2": "13319090"
}


### Login
POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
    "username": "13320001",
    "password": "123"
}


### Refresh
POST http://127.0.0.1:8000/auth/refresh/
Content-Type: application/json

{
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTYyOTMzOTMxMiwianRpIjoiYWRlY2EyOTVmYjE0NGUwNTk1MmVhNmRmZjgyNGMzN2QiLCJ1c2VybmFtZSI6IjEzMzIwMDAxIn0.__dbwwF57b4mgpT7GgxH4mLexdXMPZt6XbW2NcDk8do"
}


### API

### List students
GET http://127.0.0.1:8000/api/students/


### List groups
GET http://127.0.0.1:8000/api/groups/


### List class year
GET http://127.0.0.1:8000/api/class-year/


### Retrieve student
GET http://127.0.0.1:8000/api/profile
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI2NzQ3NTIyLCJqdGkiOiJhMDczZGFlNzliYmI0MWMxYmY5ZWViYjNiNDViNDkxOCIsInVzZXJuYW1lIjoiMTMzMjAwMDEifQ.JZU5daDE13biqmvqBMp9Y_aFX39g3GRAmZRvw2aX2bQ


### Retrieve group
GET http://127.0.0.1:8000/api/profile-group/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI2NzQ3NTIyLCJqdGkiOiJhMDczZGFlNzliYmI0MWMxYmY5ZWViYjNiNDViNDkxOCIsInVzZXJuYW1lIjoiMTMzMjAwMDEifQ.JZU5daDE13biqmvqBMp9Y_aFX39g3GRAmZRvw2aX2bQ


### Shop
POST http://127.0.0.1:8000/api/shop/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI2NzQ3NTIyLCJqdGkiOiJhMDczZGFlNzliYmI0MWMxYmY5ZWViYjNiNDViNDkxOCIsInVzZXJuYW1lIjoiMTMzMjAwMDEifQ.JZU5daDE13biqmvqBMp9Y_aFX39g3GRAmZRvw2aX2bQ
Content-Type: application/json

{
    "mystery_box_type": "sm"
}
