# Generated by Django 3.2.4 on 2021-06-19 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('health', models.IntegerField(default=100)),
                ('exp', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('LV1', 'Level 1'), ('LV2', 'Level 2'), ('LV3', 'Level 3')], default='LV1', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=100)),
                ('exp', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('LV1', 'Level 1'), ('LV2', 'Level 2'), ('LV3', 'Level 3')], default='LV1', max_length=3)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('health', models.IntegerField(default=100)),
                ('exp', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('LV1', 'Level 1'), ('LV2', 'Level 2'), ('LV3', 'Level 3')], default='LV1', max_length=3)),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('required', models.BooleanField()),
                ('deadline', models.DateTimeField()),
                ('max_yield', models.IntegerField(verbose_name='maximum yield')),
                ('year', models.ManyToManyField(to='sekolah.Year')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('required', models.BooleanField()),
                ('deadline', models.DateTimeField()),
                ('max_yield', models.IntegerField(verbose_name='maximum yield')),
                ('student', models.ManyToManyField(to='sekolah.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('required', models.BooleanField()),
                ('deadline', models.DateTimeField()),
                ('max_yield', models.IntegerField(verbose_name='maximum yield')),
                ('group', models.ManyToManyField(to='sekolah.Group')),
            ],
        ),
    ]
