# Generated by Django 3.2.4 on 2021-06-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskgroup',
            old_name='required',
            new_name='is_required',
        ),
        migrations.RenameField(
            model_name='taskstudent',
            old_name='required',
            new_name='is_required',
        ),
        migrations.RenameField(
            model_name='taskyear',
            old_name='required',
            new_name='is_required',
        ),
    ]
