# Generated by Django 3.2.4 on 2021-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_auto_20210620_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='max_yield',
        ),
        migrations.RemoveField(
            model_name='taskstudent',
            name='max_yield',
        ),
        migrations.RemoveField(
            model_name='taskyear',
            name='max_yield',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='max_score',
            field=models.IntegerField(default=100, verbose_name='maximum score'),
        ),
        migrations.AddField(
            model_name='taskstudent',
            name='max_score',
            field=models.IntegerField(default=100, verbose_name='maximum score'),
        ),
        migrations.AddField(
            model_name='taskstudent',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskyear',
            name='max_score',
            field=models.IntegerField(default=100, verbose_name='maximum score'),
        ),
        migrations.AlterField(
            model_name='taskstudent',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
