# Generated by Django 3.2.4 on 2021-06-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_auto_20210620_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstudent',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskstudent',
            name='is_required',
            field=models.BooleanField(),
        ),
    ]
