# Generated by Django 3.2.4 on 2021-06-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_auto_20210620_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_required', models.BooleanField()),
                ('is_finished', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(verbose_name='deadline date')),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100, verbose_name='maximum score')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='taskstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='taskyear',
            name='year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='TaskGroup',
        ),
        migrations.DeleteModel(
            name='TaskStudent',
        ),
        migrations.DeleteModel(
            name='TaskYear',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.AddField(
            model_name='task',
            name='student',
            field=models.ManyToManyField(to='sekolah.Student'),
        ),
    ]
