# Generated by Django 3.2.4 on 2021-06-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_auto_20210621_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttaskstatus',
            options={'verbose_name': 'task status', 'verbose_name_plural': 'task statuses'},
        ),
    ]
