# Generated by Django 3.2.4 on 2021-06-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_alter_studenttaskstatus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttaskstatus',
            old_name='is_finished',
            new_name='is_complete',
        ),
    ]
