# Generated by Django 3.2.4 on 2021-06-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0010_alter_student_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentTaskStatus',
            new_name='TaskStatus',
        ),
        migrations.AlterField(
            model_name='student',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='experience'),
        ),
    ]
