# Generated by Django 3.2.4 on 2021-06-27 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0011_auto_20210624_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('health', models.IntegerField(default=100)),
                ('exp', models.IntegerField(default=0, verbose_name='experience')),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(related_name='tasks', through='sekolah.TaskStatus', to='sekolah.Student'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='sekolah.student'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='sekolah.task'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sekolah.group'),
        ),
    ]
