# Generated by Django 3.2.4 on 2021-06-27 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0012_auto_20210627_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_required', models.BooleanField()),
                ('deadline', models.DateTimeField(verbose_name='deadline date')),
                ('max_score', models.IntegerField(default=100, verbose_name='maximum score')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='sekolah.group')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='sekolah.grouptask')),
            ],
            options={
                'verbose_name': 'group task status',
                'verbose_name_plural': 'group task statuses',
            },
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_required', models.BooleanField()),
                ('deadline', models.DateTimeField(verbose_name='deadline date')),
                ('max_score', models.IntegerField(default=100, verbose_name='maximum score')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='sekolah.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='sekolah.studenttask')),
            ],
            options={
                'verbose_name': 'task status',
                'verbose_name_plural': 'task statuses',
            },
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='student',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.AddField(
            model_name='studenttask',
            name='students',
            field=models.ManyToManyField(related_name='tasks', through='sekolah.StudentTaskStatus', to='sekolah.Student'),
        ),
        migrations.AddField(
            model_name='grouptask',
            name='groups',
            field=models.ManyToManyField(related_name='tasks', through='sekolah.GroupTaskStatus', to='sekolah.Group'),
        ),
    ]
