# Generated by Django 3.2.4 on 2021-06-29 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0013_auto_20210627_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('health', models.IntegerField(default=100)),
                ('exp', models.IntegerField(default=0, verbose_name='experience')),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studenttaskstatus',
            options={'verbose_name': 'student task status', 'verbose_name_plural': 'student task statuses'},
        ),
        migrations.CreateModel(
            name='ClassYearTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_required', models.BooleanField()),
                ('deadline', models.DateTimeField(verbose_name='deadline date')),
                ('max_score', models.IntegerField(default=100, verbose_name='maximum score')),
                ('is_complete', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sekolah.classyear')),
            ],
            options={
                'verbose_name': 'class year task status',
                'verbose_name_plural': 'class year task statuses',
            },
        ),
    ]
