# Generated by Django 3.2.4 on 2021-06-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0014_auto_20210629_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='classyear',
            name='vision',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='classyeartask',
            name='link',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='grouptask',
            name='link',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='link',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.classyear')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment1', models.IntegerField(default=0, verbose_name='kepemimpinan')),
                ('assessment2', models.IntegerField(default=0, verbose_name='keteknikfisikaan')),
                ('assessment3', models.IntegerField(default=0, verbose_name='kemahasiswaan')),
                ('assessment4', models.IntegerField(default=0, verbose_name='solidaritas')),
                ('assessment5', models.IntegerField(default=0, verbose_name='kolaboratif')),
                ('assessment6', models.IntegerField(default=0, verbose_name='semangat menjelajah')),
                ('assessment7', models.IntegerField(default=0, verbose_name='semangat memaknai')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sekolah.student')),
            ],
        ),
    ]
