# Generated by Django 3.2.4 on 2021-07-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0016_auto_20210629_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classyear',
            options={'verbose_name': 'angkatan', 'verbose_name_plural': 'angkatan'},
        ),
        migrations.AlterModelOptions(
            name='classyeartask',
            options={'verbose_name': 'tugas angkatan', 'verbose_name_plural': 'tugas angkatan'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'kelas', 'verbose_name_plural': 'kelas'},
        ),
        migrations.AlterModelOptions(
            name='grouptask',
            options={'verbose_name': 'tugas kelas', 'verbose_name_plural': 'tugas kelas'},
        ),
        migrations.AlterModelOptions(
            name='grouptaskstatus',
            options={'verbose_name': 'status tugas kelas', 'verbose_name_plural': 'status tugas kelas'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__username'], 'verbose_name': 'peserta', 'verbose_name_plural': 'peserta'},
        ),
        migrations.AlterModelOptions(
            name='studenttask',
            options={'verbose_name': 'tugas peserta', 'verbose_name_plural': 'tugas peserta'},
        ),
        migrations.AlterModelOptions(
            name='studenttaskstatus',
            options={'verbose_name': 'status tugas peserta', 'verbose_name_plural': 'status tugas peserta'},
        ),
        migrations.AlterField(
            model_name='classyear',
            name='level',
            field=models.IntegerField(choices=[(1, 'Flotilla'), (2, 'Cavalcade'), (3, 'Fleet'), (4, 'Armada')], default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.IntegerField(choices=[(1, 'Sloop'), (2, 'Brigantine'), (3, 'Galleon'), (4, "Man o' War"), (5, 'Ship of the Line')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(choices=[(1, 'Landlubber'), (2, 'Powderboy'), (3, 'Gunner'), (4, 'Corsair'), (5, 'Boatswain'), (6, 'Quartermaster'), (7, 'First Mate'), (8, 'Captain')], default=1),
        ),
    ]
