# Generated by Django 3.2.4 on 2021-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0017_auto_20210711_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='weekly_exp',
            field=models.IntegerField(default=0, verbose_name='weekly experience'),
        ),
    ]
