# Generated by Django 3.2.4 on 2021-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0018_student_weekly_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='weekly_exp',
            field=models.IntegerField(default=0, verbose_name='weekly experience'),
        ),
    ]
