# Generated by Django 3.2.4 on 2021-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0019_group_weekly_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classyear',
            name='level',
            field=models.IntegerField(choices=[(1, 'Squadron'), (2, 'Flotilla'), (3, 'Fleet'), (4, 'Armada')], default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.IntegerField(choices=[(1, 'Galley'), (2, 'Sloop'), (3, 'Brigantine'), (4, 'Galleon'), (5, "Man o' War")], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(choices=[(1, 'Landlubber'), (2, 'Powderboy'), (3, 'Guncrew'), (4, 'Master Gunner'), (5, 'Quartermaster'), (6, 'Boatswain'), (7, 'First Mate'), (8, 'Captain')], default=1),
        ),
    ]
