# Generated by Django 3.2.4 on 2021-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0020_auto_20210714_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='has_mystery_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='potion',
            field=models.IntegerField(default=0),
        ),
    ]
