# Generated by Django 3.2.4 on 2021-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0021_auto_20210719_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='has_mystery_box',
        ),
        migrations.AddField(
            model_name='student',
            name='last_mystery_box_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
